application/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordChangeView
from . import views


urlpatterns = [
    path('old_map/', views.test, name='old_map'),
    path('', views.current_emergency, name='current_appeal'),
    path('close-emergency/<int:emergency_id>/', views.close_emergency, name='close_emergency'),
    
    path('edit/<int:cur_emg_id>/', views.current_emergency_edit, name='current_emergency_edit'),



    path('archive/', views.current_appear_archive, name='current_appear_archive'),
    path('current-emergencies/', views.current_appear_archive, name='current_emergencies'),


    path('get_emergency_boss/', views.get_emergency_boss, name='get_emergency_boss'),
    path('get_emergency_transport/', views.get_emergency_transport, name='get_emergency_transport'),

    path('journal-event/<int:pk>/<str:status>/', views.journal_event, name='journal_event'),
    path('download/<int:pk>/', views.download_file, name='download_report'),
    path('line-note/', views.line_note, name='line_note'),
    path('line-note-main/<str:date_insert>/', views.line_note_main, name='line_note_main'),
    path('line-note-record/<str:date_insert>/', views.line_note_record, name='line_note_record'),
    path('line-note-report/<str:date_insert>/', views.line_note_report, name='line_note_report'),
    path('statistics/', views.statistics, name='statistics'),
    path('stat_pdf/', views.GeneratePdf.as_view(), name='stat_pdf'),
    path('income-voice-record/', views.income_voice_record, name='income_voice_record'),
    path('knowledge-storage/', views.knowledge_storage, name='knowledge_storage'),
    path('knowledge-storage/<str:section>', views.knowledge_section, name='knowledge_section'),
    path('api/new_income_call/', views.new_income_call),
    path('api/new_income_call_end_time/', views.new_income_call_end_time),
    path('api/mark_quality/', views.mark_quality),
    path('logout/', views.logout, name='logout'),
    path('report-excel/', views.reportExcel, name='report_excel'),
    path('know/', views.knowledge_base, name='knowledge_base'),
    path('profile/', views.profileInfo, name='profile'),
    path('map/', views.map, name='map'),
    path('line-note-history/', views.line_note_history, name='not-history'),

]

call_center/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main_page/', include('application.urls'))
]

urlpatterns += [
    path('', RedirectView.as_view(url='/accounts/login/', permanent=True)),
]

urlpatterns += [
    path('accounts/password_change/done/', RedirectView.as_view(url='/main_page/', permanent=True)),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += [path('event_map/', include('event_map.urls')), ]

emergency/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register('current_emergency', views.CurrentEmergencyViewSet)
router.register('emergency_rank', views.EmergencyRankViewSet)
router.register('emergency_type', views.EmergencyTypeViewSet)
router.register('fire_category', views.ObjectCategoryViewSet)
router.register('default_event', views.DefaultEventViewSet)
router.register('journal_event', views.JournalEventViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

application/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from department_structure.models import FireDepartment
from transport.models import Transport
from city.models import City
channel_layer = get_channel_layer()



# class City(models.Model):
#     name = models.CharField(max_length=30, unique=True)

#     def __str__(self):
#         return self.name

#     class Meta:
#         ordering = ["name"]
#         verbose_name_plural = "Города"
#         verbose_name = "Город"



class BorderPost(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Посты"
        verbose_name = "Пост"


class QuestionCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name_plural = "Категория вопросов"
        verbose_name = "Категория вопроса"

    def __str__(self):
        return self.name


class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    sip_number = models.CharField(max_length=9, unique=True, null=True, blank=True)
    operator = models.BooleanField(default=True, null=True, blank=True)
    department = models.ForeignKey(FireDepartment, on_delete=models.CASCADE, null=True, blank=True,
                                   verbose_name='Пожарная часть (если не оператор)')
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Пользователи ПО"
        verbose_name = "Пользователя ПО"

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_info(sender, instance, created, **kwargs):
    if created:
        UserInfo.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_info(sender, instance, **kwargs):
    instance.userinfo.save()


class StatisticCallNumber(models.Model):
    operator = models.ForeignKey(UserInfo, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Оператор')
    date = models.DateField(null=True, blank=True, verbose_name='Дата')
    call_number = models.IntegerField(default=0, verbose_name='Кол-во принятых звонков')

    class Meta:
        verbose_name_plural = "Кол-во принятых звонков"
        verbose_name = "Кол-во принятых звонков"

    def __str__(self):
        if self.operator:
            text = ' Оператор ' + str(self.operator.sip_number) + ' на ' + str(self.date) + ' кол-во ' \
                   + str(self.call_number)
        else:
            text = ' Пограничная служба на ' + str(self.date) + ' кол-во ' + str(self.call_number)
        return text

    def save(self, *args, **kwargs):
        super(StatisticCallNumber, self).save(*args, **kwargs)
        # AFTER SAVING RECORD HERE WE SEND SOCKET MESSAGE TO FRONT END TO UPDATE DASHBOARD
        res = StatisticCallNumber.objects.filter(date=datetime.now().date())
        res_list = list()
        for rr in res:
            if rr.operator:
                res_list.append(['Оператор ' + str(rr.operator.sip_number), rr.call_number])
            else:
                res_list.append(['Переведено в ПС', rr.call_number])
        print(res_list)
        async_to_sync(channel_layer.group_send)('statistic',
                                                {'type': 'send_statics_call_number',
                                                 'operators': res_list,
                                                 })


class StatisticQuestionCategory(models.Model):
    question_category = models.ForeignKey(QuestionCategory, on_delete=models.CASCADE,
                                          verbose_name='Категория вопроса')
    date = models.DateField(null=True, blank=True, verbose_name='Дата')
    call_number = models.IntegerField(default=0, verbose_name='Кол-во принятых звонков')

    class Meta:
        verbose_name_plural = "Кол-во по категории вопросов"
        verbose_name = "Кол-во по категории вопросов"

    def __str__(self):
        return str(self.question_category.name) + ' на ' + str(self.date) + ' кол-во ' \
               + str(self.call_number)

    def save(self, *args, **kwargs):
        super(StatisticQuestionCategory, self).save(*args, **kwargs)
        # AFTER SAVING RECORD HERE WE SEND SOCKET MESSAGE TO FRONT END TO UPDATE DASHBOARD
        res = StatisticQuestionCategory.objects.filter(date=datetime.now().date())
        res_list = list()
        for rr in res:
            res_list.append([rr.question_category.name, rr.call_number])
        print(res_list)
        async_to_sync(channel_layer.group_send)('statistic',
                                                {'type': 'send_statics_question_category',
                                                 'question_category': res_list,
                                                 })

class ObjectCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name_plural = "Категории объекта"
        verbose_name = "Категория объекта"

    def __str__(self):
        return self.name

class EmergencyRank(models.Model):
    rank = models.CharField(max_length=10, unique=True)

    class Meta:
        verbose_name_plural = "Ранги"
        verbose_name = "Ранг"

    def __str__(self):
        return self.rank


class EmergencyType(models.Model):
    name = models.CharField(max_length=150, unique=True)

    class Meta:
        verbose_name_plural = "Типы"
        verbose_name = "Тип"

    def __str__(self):
        return self.name

class CurrentAppeal(models.Model):
    user_created_event = models.ForeignKey(UserInfo, on_delete=models.CASCADE,
                                           verbose_name='Пользователь кто создал путевку')
    date_of_call_start = models.DateTimeField(blank=True, null=True, verbose_name='Время начала звонка')
    date_of_call_end = models.DateTimeField(blank=True, null=True, verbose_name='Время конца звонка')
    # income_call_number = models.BigIntegerField(blank=True, null=True, verbose_name='Номер тел. клиента')
    # callback_number = models.BigIntegerField(blank=True, null=True, verbose_name='Номер для обратной связи')
    income_call_number = models.CharField(max_length=30, blank=True, null=True, verbose_name='Номер тел. клиента')
    callback_number = models.CharField(max_length=30, blank=True, null=True, verbose_name='Номер для обратной связи')
    income_call_name = models.CharField(max_length=200, blank=True, null=True, verbose_name='ФИО заявителя')
    citizenship = models.CharField(max_length=100, blank=True, null=True, verbose_name='Гражданство')
    iin = models.CharField(max_length=12, blank=True, null=True, verbose_name='ИИН заявителя')
    borderpost = models.ForeignKey(BorderPost, on_delete=models.CASCADE, null=True, blank=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=True, blank=True)


    #changing
    address = models.CharField(max_length=500, blank=True, null=True, verbose_name='Адрес')
    emergency_type = models.ForeignKey(EmergencyType, on_delete=models.CASCADE, null=True, blank=True,
                                       verbose_name='Тип выезда')
    emergency_rank = models.ForeignKey(EmergencyRank, on_delete=models.CASCADE, null=True, blank=True,
                                       verbose_name='Ранг выезда')                                       
    object_owner = models.CharField(max_length=100, blank=True, null=True, verbose_name='Владелец объекта')
    emergency_closed = models.BooleanField(default=False, verbose_name='Вызов закрыть')
    object_category = models.ForeignKey(ObjectCategory, on_delete=models.CASCADE, null=True, blank=True, 
    verbose_name='Тип объекта')


    street = models.CharField(max_length=200, blank=True, null=True, verbose_name='Улица')
    house = models.CharField(max_length=5, blank=True, null=True, verbose_name='Дом')
    flat = models.CharField(max_length=3, blank=True, null=True, verbose_name='Кв')
    email = models.EmailField(blank=True, null=True)
    question_category = models.ForeignKey(QuestionCategory, on_delete=models.CASCADE,
                                          verbose_name='Категория вопроса')
    short_question = models.TextField(max_length=500, blank=True, null=True,
                                      verbose_name='Краткая фабула вопроса обращения')
    answer_to_short_question = models.TextField(max_length=500, blank=True, null=True,
                                                verbose_name='Ответ на вопрос обращения')

    ResponsibleDepartment = (
        ('c', 'CALL ЦЕНТР'),
        ('d', 'ПОГРАНИЧНАЯ СЛУЖБА'),
    )
    responsible_department = models.CharField(max_length=1, choices=ResponsibleDepartment, default='c')
    responsible_department_person = models.CharField(max_length=150, blank=True, null=True)
    

    status = models.BooleanField(default=True, verbose_name='Рассмотрен')
    api_unique_id = models.OneToOneField('ApiData', on_delete=models.CASCADE, null=True, blank=True)

    department = models.ManyToManyField(FireDepartment, verbose_name='Пожарная часть')
    transport = models.ManyToManyField(Transport, verbose_name='Привлеченные силы и средства', blank=True)

    class Meta:
        verbose_name_plural = "Текущие обращения"
        verbose_name = "Текущее обращение"

    def __str__(self):
        return ' Карта номер ' + str(self.id)

    def save(self, *args, **kwargs):
        super(CurrentAppeal, self).save(*args, **kwargs)
        # AFTER SAVING RECORD HERE STARTS CALCULATION OF STATISTICS

        # print(self.question_category)
        # print(self.user_created_event)
        # print(self.responsible_department)

application/forms.py
from django.forms import ModelForm
#from .models import *
from transport.models import Transport
from application.models import *
#from emergency.models import CurrentEmergency


class JournalEventForm(ModelForm):
    class Meta:
        model = JournalEvent
        fields = ['event']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['event'].widget.attrs.update({'class': 'form-control'})
#
# #
class CurrentEmergencyForm(ModelForm):
    class Meta:
        model = CurrentAppeal
        fields = ['date_of_call_start', 'date_of_call_end', 'income_call_number', 'income_call_name', 'address',  'object_category', 'object_owner',
                   'short_question','emergency_type', 'emergency_rank', 'department', 'responsible_department_person' , # 'first_info_burning', 'staff',
                   'transport', ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date_of_call_start'].widget.attrs.update({'class': 'form-control'})
        self.fields['date_of_call_end'].widget.attrs.update({'class': 'form-control'})
        self.fields['income_call_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['income_call_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['address'].widget.attrs.update({'class': 'form-control'})
        #self.fields['house_kv'].widget.attrs.update({'class': 'form-control'})
        self.fields['object_category'].widget.attrs.update({'class': 'form-select'})
        self.fields['object_owner'].widget.attrs.update({'class': 'form-select'})
        self.fields['short_question'].widget.attrs.update({'class': 'form-select'})
        self.fields['emergency_type'].widget.attrs.update({'class': 'form-select'})
        self.fields['emergency_rank'].widget.attrs.update({'class': 'form-select'})
        self.fields['department'].widget.attrs.update({'class': 'form-select'})
        self.fields['responsible_department_person'].widget.attrs.update({'class': 'form-select'})
        self.fields['responsible_department_person'].label = "Руководитель тушения пожара"
 
        #self.fields['first_info_burning'].widget.attrs.update({'class': 'form-control'})
        #self.fields['staff'].widget.attrs.update({'class': 'form-select'})
        self.fields['transport'].widget.attrs.update({'class': 'form-select'})


class TransportForm(ModelForm):
    class Meta:
        model = Transport
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['brand'].widget.attrs.update({'class': 'form-select'})
        self.fields['type'].widget.attrs.update({'class': 'form-select'})
        self.fields['trans_model'].widget.attrs.update({'class': 'form-select'})
        self.fields['new_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['department'].widget.attrs.update({'class': 'form-select'})

application/templates/application/1_current_emergency_edit.html
{% extends "application/0_index.html" %}

{% block title %}Текущий выезд{% endblock %}
{% block content %}
<form method="post" action="{% url 'current_emergency_edit' cur_emg_id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <div style="text-align: center;">
        <button type="submit" class="btn btn-warning">Сохранить изменение</button>
    </div>

</form>

{% endblock %}
{% block js %}
    <script>
    $(document).ready(function(){

        $('#id_date_of_call_start').prop('readonly', true);
        $('#id_date_of_call_end').prop('readonly', true);
    });
    </script>
{% endblock %}

application/templates/application/exist_appeal.html
<div class="modal fade" id="ExistedCallModal" tabindex="-1" aria-labelledby="ExistedCallModalLabel" aria-hidden="true"
data-bs-backdrop="static" data-bs-keyboard="false">
  <div class="modal-dialog modal-xl modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <div class="row">
          <h5 class="modal-title" id="ExistedCallModalLabel">Карточка №  {{ cur_appeal_modal.id }}</h5>
      </div>

        <button type="button" class="btn-close modal-close-btn" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="text-end" style="padding-right: 20px;padding-top: 10px;">
        <a style="margin-right:20px;" href="/main_page/edit/{{ cur_appeal_modal.id }}/">Редактировать</a>
        <a style="margin-right:20px;" href="/main_page/journal-event/{{ cur_appeal_modal.id }}/edit/">Журнал событий</a>
        <a href="/main_page/close-emergency/{{ cur_appeal_modal.id }}/">Завершить заявку</a>
      </div>
      <div class="modal-body">

      <form class="row g-3 ss" method="post" action="/main_page/edit/{{ cur_appeal_modal.id }}/">
        {% csrf_token %}
        <div class="col-md-4">
          <label for="date_of_call_modal" class="form-label">Дата вызова</label>
          <input type="text" class="form-control" id="date_of_call_modal" value="{{ cur_appeal_modal.date_of_call_start | date:"d/m/Y" }}" readonly>
        </div>

       <div class="col-md-4">
          <label for="time_of_call_modal" class="form-label">Начало звонка</label>
          <input type="time" class="form-control" id="time_of_call_modal" value="{{ cur_appeal_modal.date_of_call_start| date:"H:i:s" }}" readonly>
        </div>
        <div class="col-md-4">
          <label for="time_of_call_end_modal" class="form-label">Конец звонка</label>
          <input type="time" class="form-control" id="time_of_call_end_modal" value="{{ cur_appeal_modal.date_of_call_end| date:"H:i:s" }}" readonly>
        </div>
      <div class="col-md-6">
          <label for="income_call_number_modal" class="form-label">Номер телефона заявителя</label>
          <input type="text" class="form-control" id="income_call_number_modal" value="{{ cur_appeal_modal.income_call_number }}" readonly>
        </div>
        <div class="col-md-3" style="display:none;">
          <label for="count_call_number_modal" class="form-label">Количество звонков клиента</label>
            <div style="display: flex">
              <input style="margin-right: 5px;" type="text" class="form-control" id="count_call_number_modal" value="{{ count_call_number_modal }}" readonly>
              <button type="button" class="btn btn-primary" id="show_all_call_number">Посмотреть</button>
            </div>
        </div>


        <div class="col-md-6">
          <label for="income_call_name_modal" class="form-label">ФИО заявителя</label>
          <input type="text" class="form-control" id="income_call_name_modal" value="{{ cur_appeal_modal.income_call_name }}" readonly>
        </div>

        <div class="col-11">
            <label for="address_modal" class="form-label">Адрес</label>
            <input id="address_modal"  class="form-control" name="address" type="text" size="50" value="{{ cur_appeal_modal.address }}" readonly>
        </div>
        <div class="col-1">
            <label for="flat_modal" class="form-label">Кв.</label>
            <input type="text" class="form-control" id="flat_modal" name="flat_modal" value="{%if cur_appeal_modal.flat %}{{ cur_appeal_modal.flat }}{%endif%}" {% if user.userinfo.operator%}readonly{% endif %}>
          </div>
          <div class="col">
            <label for="borderpost" class="form-label">Тип выезда:</label>
            <select class="form-select " id="emergency_type" name="emergency_type">     
                {% for item in emergency_types %}                   
                   <option value="{{item.id}}" selected="">{{item.name}}</option>                   
                {% endfor %}
            </select>
        </div>
        <div class="col">
          <label for="borderpost" class="form-label">Наименование объекта:</label>
          <select class="form-select " id="object_category" name="object_category">                
              {% for item in object_categories %}                   
                 <option value="{{item.id}}" selected="">{{item.name}}</option>                   
              {% endfor %}           
          </select>
      </div>
      <div class="col-12">
        <div class="row">
            <div class="col-6">
                <label for="borderpost" class="form-label">Ранг</label>
                <select class="form-select " id="emergency_rank" name="emergency_rank">                    
                    {% for item in emergency_ranks %}                   
                    <option value="{{item.id}}" selected="">{{item.rank}}</option>                   
                    {% endfor %}                       
                </select>
            </div>
            <div class="col-6">
                <label for="object_owner" class="form-label">Владелец объекта</label>
              
                <input type="text" class="form-control" id="object_owner" name="object_owner" value="{{cur_appeal_modal.object_owner}}">
            </div>
        </div>
    </div> 
    <div class="col-12">
      <label for="department" class="form-label">Пожарная часть</label>
      <select class="form-select select2_selection" id="department" name="department"  multiple="multiple" required>
          {% for d in departaments %}
             <option value="{{d.id}}" {% for d_select in cur_appeal_modal.department.all %}{% if d_select.id == d.id %}selected="selected"{% endif %}{% endfor %}>{{d}}</option>                   
          {% endfor %}
        
      </select>


  </div>    
  <div class="col-12">
    <label for="short_question_modal" class="form-label">Первичная информация по сообщению<</label>
    <textarea class="form-control" id="short_question_modal" rows="3" readonly>{{ cur_appeal_modal.short_question }}</textarea>
</div>
  <div class="col-12">
    <label for="responsible_department_person" class="form-label">Руководитель тушения пожара</label>
    <select class="form-select select2_selection" id="transport" name="transport1">
        <option value="">{{boss.staff}}</option>
    </select>            
</div>
<div class="col-12">
    <label for="transport" class="form-label">Силы и средства</label>
    <select class="form-select select2_selection" id="transport" name="transport" multiple="multiple">                
        {% for t in transport %}
           <option value="{{ t.id }}" {%if forloop.counter == 1%}selected{% endif %}>{{ t }}</option>
        {% endfor %}            
 </select>
</div>
        <div class="col-md-2" style="display:none;">
          <label for="iin_modal" class="form-label">ИИН клиента</label>
          <input type="text" class="form-control" maxlength="12" id="iin_modal" name="iin_modal" value="{%if cur_appeal_modal.iin %}{{ cur_appeal_modal.iin }}{%endif%}" {% if user.userinfo.operator%}readonly{% endif %}>
        </div>
        <div class="col-md-3" style="display:none;">
          <label for="email_modal" class="form-label">Адрес эл.почты</label>
          <input type="text" class="form-control" id="email_modal" name="email_modal" value="{%if cur_appeal_modal.email %}{{ cur_appeal_modal.email }}{%endif%}" {% if user.userinfo.operator%}readonly{% endif %}>
        </div>
        <div class="col-md-3" style="display:none;">
          <label for="callback_number_modal" class="form-label">Номер для обратной связи</label>
          <input type="text" class="form-control" id="callback_number_modal" name="callback_number_modal" value="" {% if user.userinfo.operator%}readonly{% endif %}>
        </div>

        <div class="col-md-2" style="display:none;">
            <label for="citizenship_modal" class="form-label">Гражданство</label>
            <input type="text" class="form-control" id="citizenship_modal" name="citizenship_modal" value="{%if cur_appeal_modal.citizenship %}{{ cur_appeal_modal.citizenship }}{%endif%}" {% if user.userinfo.operator%}readonly{% endif %}>
        </div>
        <div class="col-md-5" style="display:none;">
            <div class="row">
                <div class="col">
                    <label for="city_modal" class="form-label">Город</label>
                    <input class="form-control" type="text" id="city_modal" name="city_modal" value="{%if cur_appeal_modal.city %}{{ cur_appeal_modal.city.name }}{%endif%}" readonly>
                </div>
                <div class="col">
                    <label for="borderpost_modal" class="form-label">Пограничный пост</label>
                    <input class="form-control" type="text" id="borderpost_modal" value="{{ cur_appeal_modal.borderpost.name }}" readonly>
                </div>
            </div>

        </div>
        <div class="col-md-5">
          <div class="row" >

              <div class="col-8" style="display:none;">
                <label for="street_modal" class="form-label">Улица</label>
                <input type="text" class="form-control" id="street_modal" name="street_modal" value="{%if cur_appeal_modal.street %}{{ cur_appeal_modal.street }}{%endif%}" {% if user.userinfo.operator%}readonly{% endif %}>
              </div>
              <div class="col-2" style="display:none;">
                <label for="house_modal" class="form-label">Дом</label>
                <input type="text" class="form-control" id="house_modal" name="house_modal" value="{%if cur_appeal_modal.house %}{{ cur_appeal_modal.house }}{%endif%}" {% if user.userinfo.operator%}readonly{% endif %}>
              </div>

          </div>
        </div>

        <div class="col-6" style="display:none;">
            <label for="question_category_modal" class="form-label">Категория вопроса</label>
            <input type="text" class="form-control" id="question_category_modal" value="{{ cur_appeal_modal.question_category.name }}" readonly>
        </div>
        <div class="col-6" style="display:none;">
            <label for="operator_name_modal" class="form-label">ФИО оператора call центра</label>
            <input type="text" class="form-control" id="operator_name_modal" value="{{ cur_appeal_modal.user_created_event.user.last_name }} {{ cur_appeal_modal.user_created_event.user.first_name }}" readonly>
        </div>

        {% if cur_appeal_modal.api_unique_id %}
        <div style="display:none;">
            <label class="form-label" for="audio-row">Аудио-запись разговора</label>
            <div id="audio-row" class="modal-row">
                <div class="audio-row-group" id="audio_exist_{{ cur_appeal_modal.api_unique_id }}">
                    <audio controls>
                      <source src="/static/audio/{{ cur_appeal_modal.api_unique_id }}.wav" type="audio/wav">
                    </audio>
                    <a href="/static/audio/{{ cur_appeal_modal.api_unique_id }}.wav"  class="btn btn-primary" style="margin: 10px;" download>Скачать</a>
                </div>

            </div>
        </div>
        {% endif %}



        <div class="col-11">
               {# Sorry I could not align the button to right#}
        </div>
        <div class="col-1" style="display:none;">
            <!-- Button trigger modal -->
            <p id="trans_button" class="fake_button" data-bs-toggle="modal" data-bs-target="#answer_to_short_question_modal">Ответ</p>
        </div>
        <div class="col-6" style="display:none;">
            <label for="responsible_depart_modal" class="form-label">Уполномоченное подразделение</label>
            <input type="text" class="form-control" id="responsible_depart_modal" value="{{ cur_appeal_modal.get_responsible_department_display }}" readonly>


        </div>
        <div class="col-6" style="display:none;">
            <label for="responsible_department_person_modal" class="form-label">Ф.И.О. должностного лица</label>
            <input type="text" class="form-control" name="responsible_department_person_modal" id="responsible_department_person_modal"
            value="{% if cur_appeal_modal.responsible_department_person %}{{ cur_appeal_modal.responsible_department_person }}{% endif %}" required {% if user.userinfo.operator%}readonly{% endif %}>
        </div>
        {% if user.userinfo.operator == False %}
        <div class="col-12">
            <div class="d-grid gap-2">
                <button class="btn btn-primary" type="submit">СОХРАНИТЬ КАРТОЧКУ ВОПРОС РЕШЕН</button>
            </div>
        </div>
        {% endif %}
        {# HIDDEN INPUT VALUES #}
          <input type="hidden" name="answer_to_short_question" id="answer_to_short_question">
          <input type="hidden" name="appeal_modal_id_is" id="appeal_modal_id_is" value="{{ cur_appeal_modal.id }}">
      </form>
      </div>
      <div class="modal-footer">
        
        
        
        
        <button type="button" class="btn btn-warning modal-close-btn" data-bs-dismiss="modal">Закрыть окно</button>
      </div>

    </div>
  </div>
</div>

<script>
    $(".save-changes").click(function(){
        $(".ss").submit();
    });
</script>

application/templates/application/map.html
<!DOCTYPE html>
<html>
<head>
    <title>Поиск организаций и геопоиск</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!--
        Укажите свой API-ключ. Тестовый ключ НЕ БУДЕТ работать на других сайтах.
        Получить ключ можно в Кабинете разработчика: https://developer.tech.yandex.ru/keys/
    -->
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=<ваш API-ключ>" type="text/javascript"></script>
    <script src="search_control_ppo.js" type="text/javascript"></script>
	<style>
        html, body, #map {
            width: 100%; height: 100%; padding: 0; margin: 0;
        }
    </style>
</head>
<body>
<div id="map"></div>
</body>
</html>